### ISSUE TITLE
Rethink user experience of nsfw filter extension

### ISSUE THREAD

**Issue by YegorZaremba** [navendu-pottekkat/nsfw-filter#10]
## Current Behavior

Browser load page, if we have some NSFW images on page, in most cases we should wait more than 0.5 second to analize, fetch unsplash images and DOM redrawing. I mean our users have already seen NSFW content, however was not expected for them

## Possible Solution

How i see logic:
1) When DOM loaded we should hide all images (f.e. css way - `visibility: hidden`), cause we don't know are images safe or not
2) Analyze all images
3) If image safe, change `visibility` to `visible`. If not safe leave `hidden`

Yeah, probably in some cases user still can see NSFW content for a while, but definitely time will decreased. Why I think its better? We increase performance due to not fetch random unsplash image and user doesn't wait(with NSFW content) so long to filter images

@navendu-pottekkat what do you think about it?

p.s. I can implement it with #9

**Comment by navendu-pottekkat** [comment]
@YegorZaremba That is a good idea. I was planning on implementing it and could not yet get to it. I just wanted to get an MVP out so that everyone can contribute. You can fix it and create a PR. We will also add you to the contributors' list.

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Hey, just realised that the image is just getting hidden. How about we blur the image and add a watermark if they are found to be NSFW? Please refer the feature-preview-16-july branch for the implemented code. Since you have added the feature you could also be the one to add this functionality. What do you think?

**Comment by YegorZaremba** [comment]
@navendu-pottekkat Hi, Im not not strongly against of watermarks usage, needs to discuss more with users
But I'm sure that blurring is worse than hidden visibility, cause when image is blur you know 100% that its nsfw content, cause:
1. You still can see something unsafe, I mean you get main idea of picture (to avoid needs high percent of bluring like 97% and above)
2. You definitely sure that its content is unsafe, so you think my NSFW filter works fine and etc. But when ML model fail(remember about 90-95% of success) you will be curious about why, my filter not good enough?

What we got if we just hide image
1. Users completely don't see unsafe content. Maybe also disable clicking of image is good idea
2. Users dont know reason of it, probably bad connection or website problems or nsfw filter, thay dont know for sure. So if nsfw filter fails in one specific image case - it will not a disaster for them, they are expect see some unsafe content as before

I'll check `feature-preview-16-july` branch in 72hrs, could you please create a PR to move conversation of it over there

Also if you have reasons to use watermarks and blurring, could you please create a github ticket to describe your point of view, probably some users give feedback too

ps. If we talk about watermarks as a way of marketing for the extension, not sure that its great idea, cause in most cases only advanced users install extensions, not sure that they will be great with one more label in their life. But I also have a wish to promote this extension (after strong beta version), so I hope I'll create a ticket with description and progress points of how to do it, according to [article](https://hackernoon.com/how-to-promote-your-github-project-1b39a7eee841)

**Comment by navendu-pottekkat** [comment]
@YegorZaremba The only concern I have is that the users won't know if the content was NSFW. They may think that there is a loading issue. So what I wanted was to let the users choose how they want the image to be filtered. The idea I had was these three:

- Blur the image
- Add a watermark
- Replace the image

The user can set this from the extension popup. I have built a UI for that in the ```feature-preview-16-july``` branch. We could add the hide image option also. We need to discuss more about this. 

But I agree with you that we have to keep the extension simple. So just hiding them would work in that case. We could move the conversation to a common channel so we can communicate better. You could get in touch through the email in my GitHub profile.

We will work on the new features on a separate branch. The ```feature-preview-16-july``` branch is outdated and not many changes were made there. Only the design of the popup was implemented.

**Comment by YegorZaremba** [comment]
Yeah, popup menu with options how users can handle nsfw content - awesome idea

**Comment by navendu-pottekkat** [comment]
> Yeah, popup menu with options how users can handle nsfw content - awesome idea

@abhirammltr is working on this but having some issues. We will create a slack channel and let's communicate there
