### ISSUE TITLE
Add to NSFWJS for free marketing

### ISSUE THREAD

**Issue by GantMan** [navendu-pottekkat/nsfw-filter#4]
It would be readily accepted if you added a link to this project as a PR on NSFWJS

**Comment by navendu-pottekkat** [comment]
Sure! I will add it! Should I make a pull req?

**Comment by navendu-pottekkat** [comment]
And where should I add it?

**Comment by GantMan** [comment]
You can add it as one of the examples, or below that in the "MORE" section.

**Comment by navendu-pottekkat** [comment]
Okay! I will make a pull req

**Comment by navendu-pottekkat** [comment]
I have made a pull req

**Comment by navendu-pottekkat** [comment]
Would you mind if I tagged you in a LinkedIn post?

**Comment by GantMan** [comment]
Tag away!  SOunds like a plan!

**Comment by navendu-pottekkat** [comment]
https://www.linkedin.com/posts/navendup_navendu-pottekkatnsfw-filter-activity-6689531508220411905-lUw2
