### ISSUE TITLE
Add to Made With ML Site

### ISSUE THREAD

**Issue by GantMan** [navendu-pottekkat/nsfw-filter#8]
You should share this work on https://madewithml.com/

You can even reference NSFWJS which is on there - https://madewithml.com/collections/3302/projects/?sortby=latest

Great work here!   I hope you can share it with everyone!

**Comment by navendu-pottekkat** [comment]
Hi Gant,

I will definitely share this! Thanks again for the help and the awesome
model!

Navendu

**Comment by navendu-pottekkat** [comment]
@GantMan Here is the project in Made with ML : https://madewithml.com/projects/1911/nsfw-filter/
