### ISSUE TITLE
Increase performance

### ISSUE THREAD

**Issue by YegorZaremba** [navendu-pottekkat/nsfw-filter#9]
## Expected Behavior
Processing images faster

## Current Behavior
Slow, buggy for human eye

## Possible Solution
I see 2 bottlenecks:
1) We have [3 prepared method](https://github.com/navendu-pottekkat/nsfw-filter/blob/master/src/content.js#L32), better to combine in one loop 
2) Probably better to use `DOMContentLoaded` event instead of `load` [line in code](https://github.com/navendu-pottekkat/nsfw-filter/blob/master/src/content.js#L69) 

## Steps to Reproduce (for bugs)

1. Go to test website in README
## Your Environment

* Version used: v0.2.3-beta
* Browser Name and version: Version 84.0.4147.89 (Official Build) (64-bit)
* Operating System and version: Ubuntu 20.04 LTS
* Link to your project: n/a

**Comment by navendu-pottekkat** [comment]
@YegorZaremba Could you fix this issue and make a PR?
